// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2237IQgmv-F4DHnKB5MWJZgDM4BU4x4o',
    appId: '1:670039143562:web:b285777d39aab8adc62973',
    messagingSenderId: '670039143562',
    projectId: 'oven2door',
    authDomain: 'oven2door.firebaseapp.com',
    storageBucket: 'oven2door.firebasestorage.app',
    measurementId: 'G-TC6K1YL9VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsuB9iC79iQMn3jC9kEiY11ciKz4Wohhg',
    appId: '1:670039143562:android:e386ee5848e71394c62973',
    messagingSenderId: '670039143562',
    projectId: 'oven2door',
    storageBucket: 'oven2door.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzkP0qS1JM8mj8r0MfuLf2C4mz0d5ON8s',
    appId: '1:670039143562:ios:c884676e5501a27bc62973',
    messagingSenderId: '670039143562',
    projectId: 'oven2door',
    storageBucket: 'oven2door.firebasestorage.app',
    iosBundleId: 'com.example.oven2doorMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzkP0qS1JM8mj8r0MfuLf2C4mz0d5ON8s',
    appId: '1:670039143562:ios:c884676e5501a27bc62973',
    messagingSenderId: '670039143562',
    projectId: 'oven2door',
    storageBucket: 'oven2door.firebasestorage.app',
    iosBundleId: 'com.example.oven2doorMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2237IQgmv-F4DHnKB5MWJZgDM4BU4x4o',
    appId: '1:670039143562:web:158ca66e7818d4fec62973',
    messagingSenderId: '670039143562',
    projectId: 'oven2door',
    authDomain: 'oven2door.firebaseapp.com',
    storageBucket: 'oven2door.firebasestorage.app',
    measurementId: 'G-7PZZ2H0Q59',
  );
}
